### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by stphn** [electerious/basicGrid#13]
Hi Tobias,

I am getting a lot of warnings while using your grid.
Maybe it is time to rework it. 

Docs:
https://sass-lang.com/documentation/breaking-changes/slash-div

---

For example:

``` scss
margin: 0 $basicGrid__gutter/-2;
```

Should become:

``` scss
@use "sass:math";
margin: 0 math.div($basicGrid--gutter, -2);
```

Hope it helps.

S

**Comment by electerious** [comment]
Version 3.1.5 has been published and should fix the deprecation warning. Please let me know if everything works.

**Comment by stphn** [comment]
Works like a charm!
Thanks
