### ISSUE TITLE
hide-on, show-on only applies to columns, would be nice for it to apply to rows as well.

### ISSUE THREAD

**Issue by edsurge-cory** [electerious/basicGrid#7]

**Comment by electerious** [comment]
Agree. PR welcome.

**Comment by ysanmiguel** [comment]
Great project mate, thank you very much.
I think some classes should be ready to use globally and not linked to the **.row .column** classes, sometimes is necessary add those classes to objects inside the **.columns** and not to the **.columns**. 

visibility classes for children's inside **.columns**:

```
.hide-on-large{
        display:none
}

instead:

.row .column.hide-on-large{
        display:none
}
```

and float classes for children's inside **.columns**:

```

.float-right {
    margin-left: auto;
}
```

**Comment by electerious** [comment]
@ysanmiguel Glad you like it :) I agree that those classes would be helpful globally, but basicGrid tries to be minimal and shouldn't expose more classes than necessary.

**Comment by electerious** [comment]
Done :)

https://github.com/electerious/basicGrid#show-and-hide
https://github.com/electerious/basicGrid/blob/master/CHANGELOG.md#310---2018-05-18
