### ISSUE TITLE
Question: CDN-hosted?

### ISSUE THREAD

**Issue by mjswensen** [electerious/basicGrid#8]
Hi @electerious ,

I love basicGrid and have been using it on all of my projects lately. 🙌  Excellent work!

Do you know if basicGrid is hosted on a CDN anywhere? I have been bundling it in with my sites for now (see [themer.mjswensen.com](https://themer.mjswensen.com)) but would love to reference a CDN-hosted copy if available.

Keep up the great work!

**Comment by MartinKolarik** [comment]
You can use [jsDelivr](https://www.jsdelivr.com/package/npm/basicgrid):
https://cdn.jsdelivr.net/npm/basicgrid@3.0.0/dist/basicGrid.min.css

**Comment by mjswensen** [comment]
Excellent! Thank you, @MartinKolarik and @LukasDrgon !
